{
 "title": "APM Dashboard WCF",
 "description": "Enhanced dashboard with services data",
 "tags": [ "dotnet" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(service_up,service_name)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(service_up{service_name=~\"$service\"},deployment_environment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\", http_response_status_code=~\"4..|5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\", http_response_status_code=~\"4..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval]))",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\", http_response_status_code=~\"5..\"}[$__rate_interval]) or vector(0)) / sum(rate(http_server_request_duration_seconds_bucket{service_name=~\"$service\", deployment_environment=~\"$environment\"}[$__rate_interval]))",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kestrel_active_connections{service_name=~\"$service\", deployment_environment=~\"$environment\"})",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Current Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{service_name=~\"$service\", deployment_environment=~\"$environment\"})",
     "legendFormat": "active requests"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "countAll" ] } },
   "targets": [
    {
     "filters": [
      { "id": "55446aa0", "operator": "=", "scope": "span" }
     ],
     "limit": 90000,
     "metricsQueryType": "range",
     "query": "{resource.service.name=~\"$service\" && resource.deployment.environment=\"$environment\"}",
     "spss": 1,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Total Unhandled Exceptions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "countAll" ] } },
   "targets": [
    {
     "filters": [
      { "id": "d90b7bb1", "operator": "=", "scope": "span" },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "$service" ]
      }
     ],
     "limit": 99999,
     "metricsQueryType": "range",
     "query": "{resource.service.name=~\"$service\" && resource.deployment.environment=\"$environment\" && (status=error )}",
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Top requests by duration",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "limit": 99999,
     "metricsQueryType": "range",
     "query": "{resource.service.name=~\"$service\" && resource.deployment.environment=\"$environment\" && duration>1s}",
     "spss": 1,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service\",deployment_environment=~\"$environment\"} | json | logfmt | drop __error__, __error_details__"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "piechart",
   "description": "Application logs by severity level",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(detected_level) (count_over_time({service_name=~\"$service\",deployment_environment=~\"$environment\"}[$__auto]))",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "filters": [
      { "id": "2e5c65b0", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=~\"$service\" && resource.deployment.environment=~\"$environment\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}