{
 "title": "Error Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(fastapi_app_info,app_name)"
    }
   },
   { "name": "loglevel", "label": "Log Level", "query": "DEBUG,INFO,WARNING,ERROR" }
  ]
 },
 "panels": [
  {
   "title": "Total log count",
   "type": "stat",
   "description": "Current total number of logs - filtered by app_name and loglevel",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter @timestamp >= $__from and @timestamp <= $__to\n| filter @logStream like /(?i)$app_name/\n| stats count() as total_logs",
     "logGroups": [
      {
       "arn": "/aws/eks/unity-cluster-prod/prod",
       "name": "/aws/eks/unity-cluster-prod/prod"
      }
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "Log level distribution",
   "type": "piechart",
   "description": "Distribution of logs by severity level",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "fields @message\n| filter @timestamp >= $__from and @timestamp <= $__to\n| filter @logStream like /(?i)$app_name/\n| parse @message /(?<level>ERROR|WARNING|INFO|DEBUG)/\n| stats count() as count by level",
     "logGroups": [
      {
       "arn": "/aws/eks/unity-cluster-prod/prod",
       "name": "/aws/eks/unity-cluster-prod/prod"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "level" ]
    }
   ]
  },
  {
   "title": "Log volume over time",
   "type": "timeseries",
   "description": "Total log count in 5-minute intervals - filtered by app_name and loglevel",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "fields @timestamp\n| filter @timestamp >= $__from and @timestamp <= $__to\n| filter @logStream like /(?i)$app_name/\n| filter @message like /$loglevel/\n| stats count() as log_count by bin(5m)",
     "logGroups": [
      {
       "arn": "/aws/eks/unity-cluster-prod/prod",
       "name": "/aws/eks/unity-cluster-prod/prod"
      }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(5m)" ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(status_code, app_name, path) ((fastapi_responses_total{job=~\"$app_name\", status_code=~\"4..|5..\"}))",
     "legendFormat": "{{status_code}} - {{app_name}} - {{path}}"
    }
   ]
  },
  {
   "title": "Failed Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "filters": [
      { "id": "d8b018df", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": []
      },
      {
       "id": "status",
       "isCustomValue": false,
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=~\"$app_name\" && status=error }",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "All application logs",
   "type": "logs",
   "description": "Complete log stream from CloudWatch - filtered by app_name and loglevel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expression": "fields @timestamp, @message, @logStream\n| filter @timestamp >= $__from and @timestamp <= $__to\n| filter @logStream like /(?i)$app_name/\n| filter @message like /$loglevel/\n| sort @timestamp desc",
     "logGroups": [
      {
       "arn": "/aws/eks/unity-cluster-prod/prod",
       "name": "/aws/eks/unity-cluster-prod/prod"
      }
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  }
 ]
}